const { Router } = require("express");
const health = require("./health");
const auth = require("./auth");
const adminUsers = require("./adminUsers");
const associations = require("./associations");
const clubs = require("./clubs");
const athletes = require("./athletes");
const coaches = require("./coaches");
const referees = require("./referees");
const publicClubs = require("./publicClubs");
const publicJoin = require("./publicJoin");
const events = require("./events");
const trainingModules = require("./trainingModules");
const katas = require("./katas");
const karateStyles = require("./karateStyles");
const coachRoles = require("./coachRoles");
const uploads = require("./uploads");
const settings = require("./settings");
const publicBranding = require("./publicBranding");
const adminVenues = require("./adminVenues");
const venues = require("./venues");
const squads = require("./squads");
const groups = require("./groups");

const router = Router();

router.use("/health", health);
router.use("/auth", auth);
router.use("/admin/users", adminUsers);
router.use("/admin/associations", associations);
router.use("/admin/clubs", clubs);
router.use("/athletes", athletes);
router.use("/admin/coaches", coaches);
router.use("/admin/referees", referees);
router.use("/public/clubs", publicClubs);
router.use("/public/join", publicJoin);
router.use("/events", events);
router.use("/training-modules", trainingModules);
router.use("/katas", katas);
router.use("/karate-styles", karateStyles);
router.use("/coach-roles", coachRoles);
router.use("/uploads", uploads);
router.use("/admin/settings", settings);
router.use("/public/branding", publicBranding);
router.use("/admin/venues", adminVenues);
router.use("/venues", venues);
router.use("/squads", squads);
router.use("/groups", groups);

module.exports = router;
